---
title: "SG Police Cams"
author: "Timothy Lee"
date: "18/05/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(readr)

library(rgdal)
library(leaflet)
library(htmlwidgets)
```

## Speed Cams

```{r message = FALSE}
all_speed_cams <- read_csv("location-of-speed-enforcement-cameras/location-of-speed-cameras-in-singapore.csv")
```



```{r}
popup_speed <- paste("Location:", all_speed_cams$location, "<br>",
                     "Type of Speed Cam:", all_speed_cams$type_of_speed_camera, "<br>")

sg_base_speedcams <- leaflet() %>% 
  addProviderTiles(provider = "OneMapSG.Grey") %>% 
  setView(lat = 1.352754, lng = 103.866692, zoom = 11) %>%
  setMaxBounds(lat1 = 1.157170,
               lat2 = 1.476471,
               lng1 = 103.588712,
               lng2 = 104.1) %>%
  addCircleMarkers(~location_longitude,
                   ~location_latitude,
                   color = "#f07b0e",
                   radius = 5,
                   group = "Speed Cameras",
                   popup = popup_speed,
                   fillOpacity = 0.5,
                   stroke = FALSE,
                   data = all_speed_cams
                   )

sg_base_speedcams
```

## Red Light Cams

```{r}
red_light_cams <- readOGR(dsn = "singapore-police-force-digital-traffic-red-light-cameras/.",
                          layer = "SPF_DTRLS")
```

```{r}
popup_rl <- paste("Location:", red_light_cams@data$DESCP, "<br>",
                  "Direction of Travel:", red_light_cams@data$ROAD_NAME, "towards", red_light_cams@data$DIRECTION, "<br>"
                  )

sg_speed_rl_cams <- sg_base_speedcams %>%
  addCircleMarkers(data = red_light_cams@data,
                   lat = ~LATITUDE,
                   lng = ~LONGITUDE,
                   color = "red",
                   group = "Red Light Cameras",
                   popup = popup_rl,
                   radius = 5,
                   fillOpacity = 0.5,
                   stroke = FALSE) %>%
  addLegend(colors = c("#f07b0e", "red"), 
            labels = c("Speed Cameras", "Red Light Cameras"),
            values = NULL,
            position = "topright",
            title = "Camera Type") %>%
  addLayersControl(overlayGroups = c("Speed Cameras", "Red Light Cameras"))

sg_speed_rl_cams
```


```{r}

```

